-- IETI Lead Generation Tables
-- Run in Supabase SQL Editor

-- Table: flood events detected by NOAA monitoring
CREATE TABLE IF NOT EXISTS ieti_flood_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  alert_id TEXT UNIQUE NOT NULL,
  event_type TEXT NOT NULL,
  severity TEXT,
  certainty TEXT,
  urgency TEXT,
  headline TEXT,
  description TEXT,
  instruction TEXT,
  affected_zones TEXT[],
  affected_counties TEXT[],
  rainfall_inches NUMERIC,
  gauge_station_id TEXT,
  gauge_level_ft NUMERIC,
  gauge_status TEXT,
  fema_flood_zone TEXT,
  coordinates JSONB,
  satellite_data JSONB,
  leads_generated INTEGER DEFAULT 0,
  outreach_sent INTEGER DEFAULT 0,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  processed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: leads generated by both systems
CREATE TABLE IF NOT EXISTS ieti_leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT NOT NULL CHECK (source IN ('flood_radar', 'new_homebuyer')),
  owner_name TEXT,
  owner_phone TEXT,
  owner_email TEXT,
  property_address TEXT,
  property_city TEXT,
  property_state TEXT,
  property_zip TEXT,
  year_built INTEGER,
  property_type TEXT,
  lot_size_sqft INTEGER,
  assessed_value INTEGER,
  flood_zone TEXT,
  trigger_event_id TEXT,
  trigger_event_type TEXT,
  trigger_date TIMESTAMPTZ,
  rainfall_inches NUMERIC,
  outreach_channel TEXT CHECK (outreach_channel IN ('sms', 'email', 'both')),
  sms_sent_at TIMESTAMPTZ,
  sms_status TEXT DEFAULT 'pending',
  sms_sid TEXT,
  email_sent_at TIMESTAMPTZ,
  email_status TEXT DEFAULT 'pending',
  response_status TEXT DEFAULT 'none' CHECK (response_status IN ('none','delivered','opened','clicked','replied','booked','opted_out')),
  booking_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(owner_phone, source, trigger_event_id)
);

-- Table: outreach opt-outs (compliance)
CREATE TABLE IF NOT EXISTS ieti_lead_optouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone TEXT UNIQUE,
  email TEXT,
  opted_out_at TIMESTAMPTZ DEFAULT NOW(),
  source TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_flood_events_alert ON ieti_flood_events(alert_id);
CREATE INDEX IF NOT EXISTS idx_flood_events_time ON ieti_flood_events(processed_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_source ON ieti_leads(source);
CREATE INDEX IF NOT EXISTS idx_leads_phone ON ieti_leads(owner_phone);
CREATE INDEX IF NOT EXISTS idx_leads_trigger ON ieti_leads(trigger_event_id);
CREATE INDEX IF NOT EXISTS idx_leads_created ON ieti_leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_status ON ieti_leads(response_status);
CREATE INDEX IF NOT EXISTS idx_optouts_phone ON ieti_lead_optouts(phone);

-- Enable RLS
ALTER TABLE ieti_flood_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ieti_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE ieti_lead_optouts ENABLE ROW LEVEL SECURITY;

-- Policies (allow service role full access for n8n)
CREATE POLICY "Service role full access on flood_events"
  ON ieti_flood_events FOR ALL
  USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on leads"
  ON ieti_leads FOR ALL
  USING (true) WITH CHECK (true);

CREATE POLICY "Service role full access on optouts"
  ON ieti_lead_optouts FOR ALL
  USING (true) WITH CHECK (true);

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE ieti_flood_events;
ALTER PUBLICATION supabase_realtime ADD TABLE ieti_leads;
